spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host:
      port: 6379
      password:
      database: 0
      timeout: 2000
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

my:
  tokenExpireTime: 1 # 天